### PR TITLE
Upgrade to 2.0

### PR DESCRIPTION
**Pull request by levithomason**
### Pivotal Items
- [x] [upgrade to Semantic UI 2.0](https://www.pivotaltracker.com/story/show/98505308)

**Todo**
- [x] Make a build
- [x] Fix all the broken things

---
#### Heads Up!

Had to exclude the `modules/embed.{less,variables,overrides}` component as it had a 'recursive variable definition' error during build.

### CODE REVIEW

**Comment by athurman** [comment]
Just a few pieces of style feedback (style fixes can be pulled out into another PR?):
- The placeholder text within dropdowns looks off
- The modal examples within the demo page have a broken layout

**Comment by athurman** [comment]
But code review looks good, so after fixing those small changes on this PR or on a different PR this is good to go! :1234:

**Comment by levithomason** [comment]
Fixed font icon paths
Updated gh-pages branch, was missing modal override fix
Not seeing the placeholder issue, will defer to another PR.

**Comment by eanplatter** [comment]
I don't see any issues with the code, but the dropdowns in the demo are broken: http://technologyadvice.github.io/semantic-ta/docs/dist/index.html#dropdowns

**Comment by levithomason** [comment]
Dropdowns were never 'working' as this repo didn't include any JS.  So, everything is shown in its active state.

**Comment by eanplatter** [comment]
:+1:

**Pull request merged**
